enable: true
version: 9
account:
  cookie: cookie_token_v2=v2_1_TzwUSWYfBAp5B5Qp1LE3wlNCgfXJ_xg14_7hpHF4UUwkQofe18KxBPjz5m3hRZATxPYFHKaQh1HaK8O6ZfL1p1RcV5vAq0DKd2WNJgJi9yv0BHZyLUC6oAPJhAeMow;
    account_mid_v2=0dvqmwa4pr_mhy; account_id_v2=315065630; ltoken_v2=v2_VjI32oxIXu8PBAxpvmdsxrYl5om5mJ2tJENF8iYUTXlorj3QP8xGtgYKiD9itut3gWZkAG1_pi-ocCcQggj-A_fr6Wn2BrliHoEGBcan5GhJDTKeFjkPqch1XbhLym3k;
    ltmid_v2=0dvqmwa4pr_mhy; ltuid_v2=315065630; cookie_token=AI1h6vKfHZSZuhy6PpAEkMAQb3DPDpapnYbALfuQ;
    account_id=315065630; ltoken=eKLtzCNzOFKk93tSrJ0mLd0pUgnEGARHqS9l9M4p; ltuid=315065630;
    account_id=315065630; ltuid=315065630; account_mid_v2=0dvqmwa4pr_mhy; account_id_v2=315065630;
    ltmid_v2=0dvqmwa4pr_mhy; ltuid_v2=315065630; _MHYUUID=7630d5af-6a93-4a0f-91ad-62dfa0a97f13;
    DEVICEFP_SEED_ID=f8ed9b501bee29bd; DEVICEFP_SEED_TIME=1694660763216; DEVICEFP=38d7f071dcfbe;
    login_uid=315065630; login_ticket=NitsqlbmkQM1vveQuk3j4iWbCEx4R1NW676OEH5q
  login_ticket: NitsqlbmkQM1vveQuk3j4iWbCEx4R1NW676OEH5q
  stuid: '315065630'
  stoken: VXS7NZxi9q3VeMzYHMbgO0PLtW6jkjc3bMY1FWAG
mihoyobbs:
  enable: true
  checkin: true
  checkin_multi: true
  checkin_multi_list:
  - 2
  - 5
  read_posts: true
  like_posts: true
  cancel_like_posts: true
  share_post: true
games:
  cn:
    enable: true
    useragent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like
      Gecko) Chrome/116.0.0.0 Mobile Safari/537.36
    genshin:
      auto_checkin: true
      black_list: []
    honkai2:
      auto_checkin: false
      black_list: []
    honkai3rd:
      auto_checkin: false
      black_list: []
    tears_of_themis:
      auto_checkin: false
      black_list: []
    honkai_sr:
      auto_checkin: true
      black_list: []
  os:
    enable: false
    cookie: ''
    genshin:
      auto_checkin: false
      black_list: []
    honkai_sr:
      auto_checkin: false
      black_list: []
cloud_games:
  genshin:
    enable: true
    token: ''
